<a href="https://colab.research.google.com/github/LoPA607/NLP/blob/main/spam__using_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [5]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [7]:
type(X_train)

pandas.core.series.Series

In [8]:
X_train[:4]

569     Love it! Daddy will make you scream with pleas...
2838                              1's reach home call me.
4992    We made it! Eta at taunton is 12:30 as planned...
943     How about getting in touch with folks waiting ...
Name: Message, dtype: object

In [10]:
type(y_train)

pandas.core.series.Series

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
X_train_cv.shape

(4457, 7807)

In [13]:
v.get_feature_names_out()[1000:1500]

array(['anti', 'antibiotic', 'any', 'anybody', 'anymore', 'anyone',
       'anyones', 'anyplaces', 'anythiing', 'anythin', 'anything',
       'anytime', 'anyway', 'anyways', 'anywhere', 'apart', 'apartment',
       'apes', 'apeshit', 'aphex', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'apology', 'app', 'apparently', 'appeal',
       'appendix', 'applausestore', 'applebees', 'application', 'apply',
       'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'appropriate', 'approved', 'approx',
       'apps', 'appt', 'appy', 'april', 'aproach', 'apt', 'aptitude',
       'aquarius', 'ar', 'arab', 'arcade', 'archive', 'ard', 'are',
       'area', 'aren', 'arent', 'arestaurant', 'areyouunique',
       'argentina', 'argh', 'argue', 'arguing', 'argument', 'aries',
       'arise', 'arises', 'arithmetic', 'arm', 'armand', 'armenia',
       'arms', 'arng', 'arngd', 'arnt', 'around', 'aroundn', 'arr',
       'arrange', 'arranging', 'arres

In [15]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [16]:
v.vocabulary_

{'love': 4271,
 'it': 3803,
 'daddy': 2173,
 'will': 7577,
 'make': 4371,
 'you': 7769,
 'scream': 6011,
 'with': 7608,
 'pleasure': 5304,
 'am': 947,
 'going': 3218,
 'to': 6977,
 'slap': 6270,
 'your': 7775,
 'ass': 1113,
 'my': 4717,
 'dick': 2326,
 'reach': 5641,
 'home': 3517,
 'call': 1629,
 'me': 4454,
 'we': 7474,
 'made': 4346,
 'eta': 2682,
 'at': 1127,
 'taunton': 6773,
 'is': 3792,
 '12': 272,
 '30': 425,
 'as': 1093,
 'planned': 5288,
 'hope': 3529,
 'that': 6862,
 'still': 6531,
 'okday': 4967,
 'good': 3231,
 'see': 6041,
 'xx': 7717,
 'how': 3563,
 'about': 767,
 'getting': 3169,
 'in': 3684,
 'touch': 7040,
 'folks': 2958,
 'waiting': 7412,
 'for': 2975,
 'company': 1946,
 'just': 3922,
 'txt': 7143,
 'back': 1207,
 'name': 4735,
 'and': 970,
 'age': 869,
 'opt': 5019,
 'enjoy': 2632,
 'the': 6866,
 'community': 1941,
 '150p': 297,
 'sms': 6319,
 'get': 3161,
 'lions': 4181,
 'england': 2630,
 'tone': 7005,
 'reply': 5772,
 'lionm': 4179,
 'mono': 4622,
 'or': 5024,
 '

In [17]:
X_train_np=X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
np.where(X_train_np[0]!=0)

(array([ 947, 1113, 2173, 2326, 3218, 3803, 4271, 4371, 4717, 5304, 6011,
        6270, 6977, 7577, 7608, 7769, 7775]),)

In [19]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)


MultinomialNB()

In [20]:
X_test_cv=v.transform(X_test)

In [21]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       976
           1       0.95      0.95      0.95       139

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [22]:
emails=[
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [23]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])


In [24]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [25]:
y_pred=clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       976
           1       0.95      0.95      0.95       139

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

